spring:
  application:
    name: product-microservice

  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  
  jpa:
    showSql: true

logging:
  level:
    org:
      hibernate: 
        SQL: debug

server:
  port: 8082
    
